const KEY='roco-shiny-counter-v1';
const fresh=()=>({pet1:'',pet2:'',target:'',version:2,ended:false,balls:[{stock:0,added:0,used:0,end:null},{stock:0,added:0,used:0,end:null}],pools:[0,0,0],logs:[]});
let state=fresh(),previous=null,editing=null;try{const x=JSON.parse(localStorage.getItem(KEY));if(x&&x.balls?.length===2&&x.pools?.length===3&&x.pools.every(n=>Number.isSafeInteger(n)&&n>=0)&&x.balls.every(b=>['stock','added','used'].every(k=>Number.isSafeInteger(b[k])&&b[k]>=0)))state={...fresh(),...x,version:x.version??1};}catch{}
if(state.version!==2){state.balls=state.balls.map(b=>({stock:b.stock+b.used,added:b.added,used:0,end:null}));state.version=2;state.ended=false;state.logs=[];}
const poolNames=['家族池','系别池','世界池'],ballNames=['条件球','赛季球'];
const $=id=>document.getElementById(id);let toastTimer;
function toast(t){$('toast').textContent=t;$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',3000)}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$('save').textContent='本机自动保存'}catch{$('save').textContent='保存失败，请勿关闭页面'}}
function act(text,fn){previous=structuredClone(state);fn();state.logs.unshift({text,time:new Date().toISOString()});state.logs=state.logs.slice(0,8);save();render()}
function count(i){if(!Number.isInteger(i)||i<0||i>2)throw Error('请选择有效的池');if(state.pools[i]>=Number.MAX_SAFE_INTEGER){toast('次数过大，请校正次数');return false}act(poolNames[i]+' +1',()=>{state.pools[i]++});if(state.pools[i]===80)toast(poolNames[i]+'已到80次保底！');return true}
function achievement(counts){const most=Math.max(...counts),names=poolNames.filter((_,i)=>counts[i]===most);const talent=most<=20?'了不起':most<=40?'相当好':most<=60?'还不错':'一般般';return `恭喜小洛克通过${names.join(' / ')}${names.length>1?'（次数并列最多）':''}获得了异色精灵！这次是${talent}的天分！`;}
function render(){
for(const k of ['pet1','pet2','target'])if($(k).value!==state[k])$(k).value=state[k];
$('total').textContent=state.balls.reduce((n,b)=>n+b.stock,0);
$('pools').innerHTML=state.pools.map((n,i)=>`<article class="pool"><div class="pool-top"><div class="pool-name"><span class="pool-index">0${i+1}</span>${poolNames[i]}</div><button class="text-button" data-edit="progress" data-index="${i}">校正次数</button></div><div class="progress-row"><div class="count">${n}<small>/ 80</small></div><span class="remaining">${n>80?'已超过保底 '+(n-80)+' 次':n===80?'已到保底 ✦':'距保底还差 '+(80-n)+' 次'}</span></div><progress value="${Math.min(n,80)}" max="80" aria-label="${poolNames[i]}保底进度"></progress><div class="pool-bottom"><button class="text-button" data-edit="reset" data-index="${i}">出异色 / 重置</button><button class="primary" data-count="${i}">＋ 记录一次</button></div></article>`).join('');
$('balls').innerHTML=state.balls.map((b,i)=>`<div class="ball"><div class="ball-head"><span>${ballNames[i]}</span><span class="stock">${b.stock}</span></div><div class="ball-stats">开始 ${b.stock-b.added} + 补充 ${b.added} = 总计 ${b.stock}</div><div class="ball-actions"><button data-edit="stock" data-index="${i}" ${state.ended?'disabled':''}>填写开始球数</button><button data-edit="add" data-index="${i}" ${state.ended?'disabled':''}>＋ 补球</button></div></div>`).join('');
$('finish').textContent=state.ended?'修改结束球数':'结束刷取';$('newSession').hidden=!state.ended;
$('result').innerHTML=state.ended?`<div class="session-result"><h2>本次共用 ${state.balls.reduce((n,b)=>n+b.used,0)} 个球</h2>${state.balls.map((b,i)=>`<p>${ballNames[i]}：消耗 <b>${b.used}</b> · 剩余 ${b.end}</p>`).join('')}<p class="achievement">${achievement(state.finishedPools??state.pools)}</p></div>`:'';
$('undo').disabled=!previous;
}
for(const k of ['pet1','pet2','target']){$(k).value=state[k];$(k).addEventListener('input',e=>{state[k]=e.target.value;if(previous)previous[k]=e.target.value;save()})}
document.addEventListener('click',e=>{const c=e.target.closest('[data-count]');if(c)count(Number(c.dataset.count));const b=e.target.closest('[data-edit]');if(!b)return;const kind=b.dataset.edit,i=Number(b.dataset.index);editing={kind,i};const names={stock:'填写'+ballNames[i]+'开始球数',add:'补充'+ballNames[i],progress:'校正'+poolNames[i]+'次数',reset:'重置'+poolNames[i]};$('dialogTitle').textContent=names[kind];$('dialogText').textContent={stock:'填写本次刷取开始时的球数，已记录的补球数量会另外加上。',add:'补球会增加本次总球数，结束时一并计算消耗。',progress:'填写当前本轮次数，可超过80次，不会扣球。',reset:'只将这个池的本轮进度归零，其他池与球数不变。'}[kind];$('valueLabel').hidden=kind==='reset';$('editValue').required=kind!=='reset';$('editValue').max=kind==='progress'?Number.MAX_SAFE_INTEGER:999999999;$('editValue').min=kind==='add'?1:0;$('editValue').value=kind==='stock'?state.balls[i].stock-state.balls[i].added:kind==='progress'?state.pools[i]:'';$('editor').showModal();if(kind!=='reset')$('editValue').focus()});
$('cancel').onclick=()=>$('editor').close();$('editForm').onsubmit=e=>{e.preventDefault();const {kind,i}=editing,n=Number($('editValue').value);if(kind!=='reset'&&(!Number.isSafeInteger(n)||n<(kind==='add'?1:0)||n>(kind==='progress'?Number.MAX_SAFE_INTEGER:999999999))){toast('请输入有效的整数');return}if(kind==='reset')act(poolNames[i]+'已重置',()=>state.pools[i]=0);if(kind==='progress')act(poolNames[i]+'校正为 '+n+' 次',()=>state.pools[i]=n);if(kind==='stock')act(ballNames[i]+'开始球数设为 '+n,()=>state.balls[i].stock=n+state.balls[i].added);if(kind==='add')act(ballNames[i]+'补充 '+n+' 个',()=>{state.balls[i].stock+=n;state.balls[i].added+=n});$('editor').close()};
$('undo').onclick=()=>{if(!previous)return;state=previous;previous=null;save();render();toast('已撤销上一步')};render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_counter',description:'读取精灵、球库存和三个池的当前次数',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>structuredClone(state)})).catch(()=>{})}catch{}}

$('finish').onclick=()=>{state.balls.forEach((b,i)=>{$('end'+i).value=state.ended?b.end:''});$('finishError').textContent='';$('finishDialog').showModal();$('end0').focus()};
$('cancelFinish').onclick=()=>$('finishDialog').close();
function finishSession(values){if(!Array.isArray(values)||values.length!==2||values.some((n,i)=>!Number.isSafeInteger(n)||n<0||n>state.balls[i].stock))return false;act('结束刷取 · 共用 '+values.reduce((total,n,i)=>total+state.balls[i].stock-n,0)+' 个球',()=>{state.balls.forEach((b,i)=>{b.end=values[i];b.used=b.stock-values[i]});if(!state.ended)state.finishedPools=[...state.pools];state.ended=true});return true}
$('finishForm').onsubmit=e=>{e.preventDefault();if(['end0','end1'].some(id=>$(id).value.trim()==='')){$('finishError').textContent='请填写两种球的剩余数量。';return}if(!finishSession([Number($('end0').value),Number($('end1').value)])){$('finishError').textContent='剩余球数须为非负整数，且不能超过开始球数＋补球；如有漏记，请取消后补充。';return}$('finishDialog').close()};
$('newSession').onclick=()=>{act('开始新一轮球数记录 · 保留各池进度',()=>{state.balls=state.balls.map(()=>({stock:0,added:0,used:0,end:null}));state.pet1='';state.pet2='';state.target='';state.finishedPools=null;state.ended=false});toast('已清空球数和精灵信息，各池进度保留')};
